### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libosxfuse.2.dylib

### ISSUE THREAD

**Issue by lparkes** [jmmv/pkg_comp#1]
The macOS installer comes with the program /usr/local/bin/bindfs, but not the shared library /usr/local/lib/libosxfuse.2.dylib that bindfs needs.

I'm guessing this is just an oversight in the packing list for the package.

**Comment by jmmv** [comment]
I intentionally did not package OSXFUSE as part of the installer as that'd be quite "risky". I need to update the documentation accordingly.

Can you try to install OSXFUSE 3 separately and see if things work fine?

**Comment by lparkes** [comment]
Thanks, that works. I agree that installing parts of someone else's software is not such a great idea.

**Comment by jmmv** [comment]
I've updated the installation instructions and the blog post accordingly. Thanks for spotting this!
