### ISSUE TITLE
Can't bootstrap on macOS High Sierra because C compiler does not work

### ISSUE THREAD

**Issue by jlmuir** [jmmv/pkg_comp#25]
I can't bootstrap on macOS High Sierra.  I do the following:

```
$ sudo pkg_comp sandbox-create
$ sudo pkg_comp bootstrap
```
And the bootstrap fails like this:

```
===> Bootstrapping bmake
===> running: /bin/sh /pkg_comp/work/pkg/bootstrap/bin/install-sh -d -o root -g
wheel /pkg_comp/work/pkg/bootstrap/bmake
===> running: (cd /pkg_comp/work/pkg/bootstrap/bmake && /bin/sh configure  --pre
fix=/pkg_comp/work/pkg/bootstrap --with-default-sys-path=/pkg_comp/work/pkg/boot
strap/share/mk --with-machine-arch=x86_64 )
checking for gcc... cc -isystem /usr/include
checking for C compiler default output file name...
configure: error: in `/pkg_comp/work/pkg/bootstrap/bmake':
configure: error: C compiler cannot create executables
See `config.log' for more details.
===> exited with status 77
aborted.
```

It seems that the C compiler does not work in the sandbox.  I filed [sandboxctl issue #7](https://github.com/jmmv/sandboxctl/issues/7) for this.

**Comment by jmmv** [comment]
This should have been fixed by https://github.com/jmmv/sandboxctl/issues/7. I don't think there are any changes necessary to pkg_comp itself, other than for making a new release that depends on a newer version of sandboxctl. I'll get to that soon.
