### ISSUE TITLE
Unclear how to access build logs

### ISSUE THREAD

**Issue by truist** [jmmv/pkg_comp#3]
Per my [original comments](http://julio.meroh.net/2017/02/pkg_comp-2.0-tutorial-netbsd.html#comment-3174033375):

> It's still not clear to me how to see the output logs. It looks like only the cron job will log to /var/pkg_comp/log, but that's not clear from the blog post. ("...you can find the logs for all builds...") I also am still not clear on how to see the detailed logs from the individual packages, both during the build, and after. I found them once, but I don't remember where. (I know that's probably more of a pbulk issue, but it would help to explain it here.)

I think there's a 2x2 matrix of cases:

1a. During cron build
1b. After cron build
2a. During manual (`auto -f`) build
2b. After manual build

Ideally it would always just be "here's where the active and/or residual logs are, from outside the sandbox" but maybe it's not that easy.

**Comment by jlmuir** [comment]
+1

It would be extremely useful to have the pbulk log output preserved, preferably somewhere under `/var/pkg_comp/log`.  pbulk generates its log output in the directory specified by its `bulklog` variable which pkg_comp appears to set to `/pkg_comp/work/bulklog` in [line 370](https://github.com/jmmv/pkg_comp/blob/ef5a0b9e118709d47baa3baad5ff4c15621be1eb/pkg_comp.sh#L370).  If pkg_comp could take care of copying that out of the sandbox to a directory under `/var/pkg_comp/log`, perhaps `/var/pkg_comp/log/pbulk`, that would be great!

**Comment by jlmuir** [comment]
A workaround is possible with pull request #14 that adds hook support for a user-defined `post_build_hook` routine.  By defining that routine to copy pbulk's log out of the sandbox before the sandbox gets destroyed, pbulk's log can be accessed after pkg_comp finishes executing.  In the pull request, I give an example definition for that routine that I use on macOS.

**Comment by jmmv** [comment]
I'm playing with a fix that adds a new configuration setting that points at a location that will hold the logs, and just making pbulk dump its logs there. We can bind-mount that location; no need to deal with post-build copies.
