### ISSUE TITLE
No way to bootstrap pkg_comp without pkgsrc and/or pkgconfig

### ISSUE THREAD

**Issue by truist** [jmmv/pkg_comp#5]
Per http://julio.meroh.net/2017/02/pkg_comp-2.0-tutorial-netbsd.html#comment-3187176460, it's not currently possible to bootstrap pkg_comp without pkgsrc or pkgconfig. It would be nice if it could be done.

**Comment by jmmv** [comment]
Should be easy. As far as I know, one can "inject" the pkgconfig results to the configure script via environment variables so that configure never invokes pkgconfig itself. What I'm not sure about is if this is properly supported with the way I invoke pkgconfig to find shtk, so I'll look into it.
